// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBu5anpNxfmOJFtpDsEgaj-gkgGWVvrA',
    appId: '1:1068367724620:web:b38aa439a5143eac3834e9',
    messagingSenderId: '1068367724620',
    projectId: 'projet-64221',
    authDomain: 'projet-64221.firebaseapp.com',
    storageBucket: 'projet-64221.firebasestorage.app',
    measurementId: 'G-72D6H87VED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzM3ALcCsprzivgPNlxWu_ycqqOIgMZdA',
    appId: '1:1068367724620:android:844eb5a9cb35d6573834e9',
    messagingSenderId: '1068367724620',
    projectId: 'projet-64221',
    storageBucket: 'projet-64221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpzfgA6Yp0wjlWbVGEL0n4lxGt6hsHXI',
    appId: '1:1068367724620:ios:7fae5b0fe7d147f23834e9',
    messagingSenderId: '1068367724620',
    projectId: 'projet-64221',
    storageBucket: 'projet-64221.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpzfgA6Yp0wjlWbVGEL0n4lxGt6hsHXI',
    appId: '1:1068367724620:ios:7fae5b0fe7d147f23834e9',
    messagingSenderId: '1068367724620',
    projectId: 'projet-64221',
    storageBucket: 'projet-64221.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEBu5anpNxfmOJFtpDsEgaj-gkgGWVvrA',
    appId: '1:1068367724620:web:8e8b71926d6efbd43834e9',
    messagingSenderId: '1068367724620',
    projectId: 'projet-64221',
    authDomain: 'projet-64221.firebaseapp.com',
    storageBucket: 'projet-64221.firebasestorage.app',
    measurementId: 'G-THQ7C102Z9',
  );
}
